language: cpp
compiler: gcc
dist: trusty
sudo: required
group: edge
branches:
  only:
    - develop
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - python-dev
      - python-pip
install:
   - sudo pip install cget
   - cget install -f ./requirements.txt
script:
  - cmake --version
  - mkdir build && cd build
  - cmake -DBUILD_TESTS=1 -DCMAKE_TOOLCHAIN_FILE=../cget/cget/cget.cmake ..
  - cd ..
  - make -C build
  - make CTEST_OUTPUT_ON_FAILURE=1 test -C buld